# Site settings
title: springkid notes
email: jmgomezr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just a place to annotate ideas, works in progress and random stuff /
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://erisso.com" # the base hostname & protocol for your site
twitter_username: springkid
github_username:  springkid

# Build settings
markdown: kramdown
